--AMPLIACIÓN DE RESTRICCIONES (EJERCICIOS)
/*
CHECK
- COMPARACIÓN CON VALORES NUMÉRICOS
- COMPARACIÓN CON CADENAS DE CARACTERES
- COMPARACIÓN CON CONJUNTO DE CADENAS DE CARACTERES: IN
- FECHAS
- EXPRESIONES REGULARES: REGEXP_LIKE

NOT NULL / NULL

UNIQUE

DEFAULT
*/

--EJERCICIOS
/* 
1. CREA LA TABLA DEPT CON LOS SIGUIENTES CAMPOS
 - DEPTNO NUMBER(2,0)
 - DNAME VARCHAR2(14)
 - LOC VARCHAR2(13)
2. HAZ QUE SU CLAVE PRIMARIA SEA EL CAMPO DEPTNO Y PONLE COMO NOMBRE PK_DEPT A DICHA PK
3. CREA LA TABLA EMP CON LOS SIGUIENTES CAMPOS
    EMPNO NUMBER(4,0)
    ENAME VARCHAR2(10)
    JOB VARCHAR2(9)
    MGR NUMBER(4,0)
    HIREDATE DATE
    SAL NUMBER(7,2)
    COMM NUMBER(7,2)
4. HAZ QUE EMPNO SEA LA PK DE LA TABLA EMP
5. AÑADE UN CAMPO DEPTNO A LA TABLA EMP. LUEGO HAZ QUE ESE CAMPO SEA FK DE DEPTNO (PK) EN LA TABLA DEPT
6. CAMBIA EL NOMBRE DE LA RESTRICCIÓN PK_DEPT POR CLAVE_PRIMARIA_DEPT
7. AÑADE LAS SIGUIENTES RESTRICCIONES CHECK A LA TABLA EMP:
- EL CAMPO SAL DEBE SER MAYOR QUE CERO
- EL CAMPO ENAME TIENE QUE SER NOT NULL
- EL CAMPO JOB SOLO PUEDE SER UNO DE LOS SIGUIENTES VALORES
    - PRESIDENT
    - MANAGER
    - ANALYST
    - CLERK
    - SALESMAN
8. AÑADE UN CAMPO DNI DEL TIPO CHAR(9) QUE TENGA LA SIGUIENTE RESTRICCIÓN CHECK Y MÁSCARA: OCHO NÚMEROS Y UNA LETRA
EJ.: 11111111X
9. AÑADE OTRA RESTRICCIÓN AL CAMPO DNI QUE SEA UNIQUE
10. EL VALOR POR DEFECTO (DEFAULT) DEL CAMPO DEPTNO EN LA TABLA EMP ES 10
*/

