set SERVEROUTPUT on;
BEGIN
    DBMS_OUTPUT.PUT_LINE('HOLA MUNDO');
END;
/
DECLARE HM VARCHAR2(100):= 'HOLA MUNDO';
BEGIN

    DBMS_OUTPUT.PUT_LINE(HM);
END;
/
DECLARE HM VARCHAR2(100):= 'HOLA MUNDO ';
        NUMERO INT:=32;
BEGIN

    DBMS_OUTPUT.PUT_LINE(HM||NUMERO);
END;
/
DECLARE
    MIFECHA DATE;
    MIFECHA2 DATE:= '23/01/2026';
    NONULA NUMBER(3,2) NOT NULL:=111;
    SALE NUMBER (4,2) := 10.99;
    CLASE VARCHAR2(15):= 'CLASE DE DAMDAW';
    CE CONSTANT INT:=11;
BEGIN

END;
/
DECLARE
    NOMBREEMPLEADO EMP.ENAME%TYPE := 'TOMAS';
    MIEMPLEADO EMP%ROWTYPE;
BEGIN
    MIEMPLEADO.ENAME := 'MARIA';
    DBMS_OUTPUT.PUT_LINE(NOMBREEMPLEADO);
    DBMS_OUTPUT.PUT_LINE(MIEMPLEADO.SAL);
    DBMS_OUTPUT.PUT_LINE(MIEMPLEADO.ENAME);
END;
/
DECLARE
MICLIENTE CLIENTES%ROWTYPE;
BEGIN
SELECT ID, NOMBRE, TFNO INTO MICLIENTE FROM CLIENTES WHERE NOMBRE ='ANDRES PEREZ';
DBMS_OUTPUT.PUT_LINE(MICLIENTE.ID);
DBMS_OUTPUT.PUT_LINE(MICLIENTE.NOMBRE);
DBMS_OUTPUT.PUT_LINE(MICLIENTE.TFNO);
END;
/
DECLARE
    NOMBRE EMP.ENAME%TYPE;
    EMPLEADO EMP%ROWTYPE;
BEGIN
    SELECT ENAME INTO NOMBRE FROM EMP WHERE EMPO=7839;
    SELECT * INTO EMPLEADO FROM EMP WHERE EMPO =7698;
    DBMS_OUTPUT.PUT_LINE(EMPLEADO.ENAME|| ' '||NOMBRE);
END;
/

