set SERVEROUTPUT on;
BEGIN
    DBMS_OUTPUT.PUT_LINE('HOLA MUNDO');
END;
/
DECLARE HM VARCHAR2(100):= 'HOLA MUNDO';
BEGIN

    DBMS_OUTPUT.PUT_LINE(HM);
END;
/
DECLARE HM VARCHAR2(100):= 'HOLA MUNDO ';
        NUMERO INT:=32;
BEGIN

    DBMS_OUTPUT.PUT_LINE(HM||NUMERO);
END;
/
DECLARE
    MIFECHA DATE;
    MIFECHA2 DATE:= '23/01/2026';
    NONULA NUMBER(3,2) NOT NULL:=111;
    SALE NUMBER (4,2) := 10.99;
    CLASE VARCHAR2(15):= 'CLASE DE DAMDAW';
    CE CONSTANT INT:=11;
BEGIN

END;
/
DECLARE
    MINOMBRE EMP.ENAME%TYPE:='PEPITO';
    MIEMPLEADO EMP%ROWTYPE;
BEGIN
    MIEMPLEADO.ENAME:='PEPITO2';
    DBMS_OUTPUT.PUT_LINE(MINOMBRE);
    DBMS_OUTPUT.PUT_LINE(MIEMPLEADO.ENAME);
END;
/
